---
  - name: "create Thoth CronJob {{ cronjob_name }}"
    shell: "oc process --namespace {{ THOTH_INFRA_NAMESPACE  }} {{ cronjob_name }}-cronjob -p THOTH_SUSPEND_JOB={{ suspend | lower }} | oc apply --namespace {{ namespace }} -f -"
